"""Curated Indian cinema movie dataset.

MOVIES is a list of dictionaries with:
- title (str), year (int), era (str), and roles (dict).
- roles always contains exactly: Director, Lead Male, Lead Female,
  Music Director, and Writer.
- era groups entries into one of: Vintage, 90s, Millennium, Modern, 2021-2026.
"""

MOVIES = [
    {
        "title": "Alam Ara",
        "year": 1931,
        "era": "Vintage",
        "roles": {
            "Director": "Ardeshir Irani",
            "Lead Male": "Master Vithal",
            "Lead Female": "Zubeida",
            "Music Director": "Firozshah Mistry",
            "Writer": "Joseph David",
        },
    },
    {
        "title": "Devdas",
        "year": 1955,
        "era": "Vintage",
        "roles": {
            "Director": "Bimal Roy",
            "Lead Male": "Dilip Kumar",
            "Lead Female": "Suchitra Sen",
            "Music Director": "S. D. Burman",
            "Writer": "Nabendu Ghosh",
        },
    },
    {
        "title": "Mother India",
        "year": 1957,
        "era": "Vintage",
        "roles": {
            "Director": "Mehboob Khan",
            "Lead Male": "Raaj Kumar",
            "Lead Female": "Nargis",
            "Music Director": "Naushad",
            "Writer": "Wajahat Mirza",
        },
    },
    {
        "title": "Mughal-e-Azam",
        "year": 1960,
        "era": "Vintage",
        "roles": {
            "Director": "K. Asif",
            "Lead Male": "Dilip Kumar",
            "Lead Female": "Madhubala",
            "Music Director": "Naushad",
            "Writer": "Amanullah Khan",
        },
    },
    {
        "title": "Guide",
        "year": 1965,
        "era": "Vintage",
        "roles": {
            "Director": "Vijay Anand",
            "Lead Male": "Dev Anand",
            "Lead Female": "Waheeda Rehman",
            "Music Director": "S. D. Burman",
            "Writer": "R. K. Narayan",
        },
    },
    {
        "title": "Aradhana",
        "year": 1969,
        "era": "Vintage",
        "roles": {
            "Director": "Shakti Samanta",
            "Lead Male": "Rajesh Khanna",
            "Lead Female": "Sharmila Tagore",
            "Music Director": "S. D. Burman",
            "Writer": "Sachin Bhowmick",
        },
    },
    {
        "title": "Anand",
        "year": 1971,
        "era": "Vintage",
        "roles": {
            "Director": "Hrishikesh Mukherjee",
            "Lead Male": "Rajesh Khanna",
            "Lead Female": "Sumita Sanyal",
            "Music Director": "Salil Chowdhury",
            "Writer": "Gulzar",
        },
    },
    {
        "title": "Pakeezah",
        "year": 1972,
        "era": "Vintage",
        "roles": {
            "Director": "Kamal Amrohi",
            "Lead Male": "Raaj Kumar",
            "Lead Female": "Meena Kumari",
            "Music Director": "Ghulam Mohammed",
            "Writer": "Kamal Amrohi",
        },
    },
    {
        "title": "Bobby",
        "year": 1973,
        "era": "Vintage",
        "roles": {
            "Director": "Raj Kapoor",
            "Lead Male": "Rishi Kapoor",
            "Lead Female": "Dimple Kapadia",
            "Music Director": "Laxmikant-Pyarelal",
            "Writer": "Khwaja Ahmad Abbas",
        },
    },
    {
        "title": "Sholay",
        "year": 1975,
        "era": "Vintage",
        "roles": {
            "Director": "Ramesh Sippy",
            "Lead Male": "Dharmendra",
            "Lead Female": "Hema Malini",
            "Music Director": "R. D. Burman",
            "Writer": "Salim Khan",
        },
    },
    {
        "title": "Deewaar",
        "year": 1975,
        "era": "Vintage",
        "roles": {
            "Director": "Yash Chopra",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Parveen Babi",
            "Music Director": "R. D. Burman",
            "Writer": "Salim Khan",
        },
    },
    {
        "title": "Amar Akbar Anthony",
        "year": 1977,
        "era": "Vintage",
        "roles": {
            "Director": "Manmohan Desai",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Parveen Babi",
            "Music Director": "Laxmikant-Pyarelal",
            "Writer": "Kader Khan",
        },
    },
    {
        "title": "Don",
        "year": 1978,
        "era": "Vintage",
        "roles": {
            "Director": "Chandra Barot",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Zeenat Aman",
            "Music Director": "Kalyanji-Anandji",
            "Writer": "Salim Khan",
        },
    },
    {
        "title": "Gol Maal",
        "year": 1979,
        "era": "Vintage",
        "roles": {
            "Director": "Hrishikesh Mukherjee",
            "Lead Male": "Amol Palekar",
            "Lead Female": "Bindiya Goswami",
            "Music Director": "R. D. Burman",
            "Writer": "Rahi Masoom Raza",
        },
    },
    {
        "title": "Masoom",
        "year": 1983,
        "era": "Vintage",
        "roles": {
            "Director": "Shekhar Kapur",
            "Lead Male": "Naseeruddin Shah",
            "Lead Female": "Shabana Azmi",
            "Music Director": "R. D. Burman",
            "Writer": "Gulzar",
        },
    },
    {
        "title": "Mr. India",
        "year": 1987,
        "era": "Vintage",
        "roles": {
            "Director": "Shekhar Kapur",
            "Lead Male": "Anil Kapoor",
            "Lead Female": "Sridevi",
            "Music Director": "Laxmikant-Pyarelal",
            "Writer": "Salim Khan",
        },
    },
    {
        "title": "Qayamat Se Qayamat Tak",
        "year": 1988,
        "era": "Vintage",
        "roles": {
            "Director": "Mansoor Khan",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Juhi Chawla",
            "Music Director": "Anand-Milind",
            "Writer": "Nasir Hussain",
        },
    },
    {
        "title": "Tezaab",
        "year": 1988,
        "era": "Vintage",
        "roles": {
            "Director": "N. Chandra",
            "Lead Male": "Anil Kapoor",
            "Lead Female": "Madhuri Dixit",
            "Music Director": "Laxmikant-Pyarelal",
            "Writer": "Kamlesh Pandey",
        },
    },
    {
        "title": "Chandni",
        "year": 1989,
        "era": "Vintage",
        "roles": {
            "Director": "Yash Chopra",
            "Lead Male": "Rishi Kapoor",
            "Lead Female": "Sridevi",
            "Music Director": "Shiv-Hari",
            "Writer": "Sagar Sarhadi",
        },
    },
    {
        "title": "Parinda",
        "year": 1989,
        "era": "Vintage",
        "roles": {
            "Director": "Vidhu Vinod Chopra",
            "Lead Male": "Anil Kapoor",
            "Lead Female": "Madhuri Dixit",
            "Music Director": "R. D. Burman",
            "Writer": "Shiv Kumar Subramaniam",
        },
    },
    {
        "title": "Dil",
        "year": 1990,
        "era": "90s",
        "roles": {
            "Director": "Indra Kumar",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Madhuri Dixit",
            "Music Director": "Anand-Milind",
            "Writer": "Rajeev Kaul",
        },
    },
    {
        "title": "Saajan",
        "year": 1991,
        "era": "90s",
        "roles": {
            "Director": "Lawrence D'Souza",
            "Lead Male": "Sanjay Dutt",
            "Lead Female": "Madhuri Dixit",
            "Music Director": "Nadeem-Shravan",
            "Writer": "Reema Rakesh Nath",
        },
    },
    {
        "title": "Jo Jeeta Wohi Sikandar",
        "year": 1992,
        "era": "90s",
        "roles": {
            "Director": "Mansoor Khan",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Ayesha Jhulka",
            "Music Director": "Jatin-Lalit",
            "Writer": "Nasir Hussain",
        },
    },
    {
        "title": "Baazigar",
        "year": 1993,
        "era": "90s",
        "roles": {
            "Director": "Abbas-Mustan",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Kajol",
            "Music Director": "Anu Malik",
            "Writer": "Robin Bhatt",
        },
    },
    {
        "title": "Hum Aapke Hain Koun..!",
        "year": 1994,
        "era": "90s",
        "roles": {
            "Director": "Sooraj Barjatya",
            "Lead Male": "Salman Khan",
            "Lead Female": "Madhuri Dixit",
            "Music Director": "Raamlaxman",
            "Writer": "Sooraj Barjatya",
        },
    },
    {
        "title": "Dilwale Dulhania Le Jayenge",
        "year": 1995,
        "era": "90s",
        "roles": {
            "Director": "Aditya Chopra",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Kajol",
            "Music Director": "Jatin-Lalit",
            "Writer": "Aditya Chopra",
        },
    },
    {
        "title": "Rangeela",
        "year": 1995,
        "era": "90s",
        "roles": {
            "Director": "Ram Gopal Varma",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Urmila Matondkar",
            "Music Director": "A. R. Rahman",
            "Writer": "Neeraj Vora",
        },
    },
    {
        "title": "Raja Hindustani",
        "year": 1996,
        "era": "90s",
        "roles": {
            "Director": "Dharmesh Darshan",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Karisma Kapoor",
            "Music Director": "Nadeem-Shravan",
            "Writer": "Robin Bhatt",
        },
    },
    {
        "title": "Border",
        "year": 1997,
        "era": "90s",
        "roles": {
            "Director": "J. P. Dutta",
            "Lead Male": "Sunny Deol",
            "Lead Female": "Tabu",
            "Music Director": "Anu Malik",
            "Writer": "J. P. Dutta",
        },
    },
    {
        "title": "Judwaa",
        "year": 1997,
        "era": "90s",
        "roles": {
            "Director": "David Dhawan",
            "Lead Male": "Salman Khan",
            "Lead Female": "Karisma Kapoor",
            "Music Director": "Anu Malik",
            "Writer": "Rumi Jaffery",
        },
    },
    {
        "title": "Gupt",
        "year": 1997,
        "era": "90s",
        "roles": {
            "Director": "Rajiv Rai",
            "Lead Male": "Bobby Deol",
            "Lead Female": "Manisha Koirala",
            "Music Director": "Viju Shah",
            "Writer": "Shabbir Boxwala",
        },
    },
    {
        "title": "Dil Se..",
        "year": 1998,
        "era": "90s",
        "roles": {
            "Director": "Mani Ratnam",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Manisha Koirala",
            "Music Director": "A. R. Rahman",
            "Writer": "Mani Ratnam",
        },
    },
    {
        "title": "Kuch Kuch Hota Hai",
        "year": 1998,
        "era": "90s",
        "roles": {
            "Director": "Karan Johar",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Kajol",
            "Music Director": "Jatin-Lalit",
            "Writer": "Karan Johar",
        },
    },
    {
        "title": "Satya",
        "year": 1998,
        "era": "90s",
        "roles": {
            "Director": "Ram Gopal Varma",
            "Lead Male": "J. D. Chakravarthy",
            "Lead Female": "Urmila Matondkar",
            "Music Director": "Vishal Bhardwaj",
            "Writer": "Anurag Kashyap",
        },
    },
    {
        "title": "Ghulam",
        "year": 1998,
        "era": "90s",
        "roles": {
            "Director": "Vikram Bhatt",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Rani Mukerji",
            "Music Director": "Jatin-Lalit",
            "Writer": "Anjum Rajabali",
        },
    },
    {
        "title": "Soldier",
        "year": 1998,
        "era": "90s",
        "roles": {
            "Director": "Abbas-Mustan",
            "Lead Male": "Bobby Deol",
            "Lead Female": "Preity Zinta",
            "Music Director": "Anu Malik",
            "Writer": "Sachin Bhowmick",
        },
    },
    {
        "title": "Hum Dil De Chuke Sanam",
        "year": 1999,
        "era": "90s",
        "roles": {
            "Director": "Sanjay Leela Bhansali",
            "Lead Male": "Salman Khan",
            "Lead Female": "Aishwarya Rai",
            "Music Director": "Ismail Darbar",
            "Writer": "Sanjay Leela Bhansali",
        },
    },
    {
        "title": "Sarfarosh",
        "year": 1999,
        "era": "90s",
        "roles": {
            "Director": "John Matthew Matthan",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Sonali Bendre",
            "Music Director": "Jatin-Lalit",
            "Writer": "Hriday Lani",
        },
    },
    {
        "title": "Vaastav",
        "year": 1999,
        "era": "90s",
        "roles": {
            "Director": "Mahesh Manjrekar",
            "Lead Male": "Sanjay Dutt",
            "Lead Female": "Namrata Shirodkar",
            "Music Director": "Jatin-Lalit",
            "Writer": "Imtiaz Hussain",
        },
    },
    {
        "title": "Kaho Naa... Pyaar Hai",
        "year": 2000,
        "era": "Millennium",
        "roles": {
            "Director": "Rakesh Roshan",
            "Lead Male": "Hrithik Roshan",
            "Lead Female": "Ameesha Patel",
            "Music Director": "Rajesh Roshan",
            "Writer": "Honey Irani",
        },
    },
    {
        "title": "Hera Pheri",
        "year": 2000,
        "era": "Millennium",
        "roles": {
            "Director": "Priyadarshan",
            "Lead Male": "Akshay Kumar",
            "Lead Female": "Tabu",
            "Music Director": "Anu Malik",
            "Writer": "Neeraj Vora",
        },
    },
    {
        "title": "Dil Chahta Hai",
        "year": 2001,
        "era": "Millennium",
        "roles": {
            "Director": "Farhan Akhtar",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Preity Zinta",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Farhan Akhtar",
        },
    },
    {
        "title": "Lagaan",
        "year": 2001,
        "era": "Millennium",
        "roles": {
            "Director": "Ashutosh Gowariker",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Gracy Singh",
            "Music Director": "A. R. Rahman",
            "Writer": "Kumar Dave",
        },
    },
    {
        "title": "Kabhi Khushi Kabhie Gham",
        "year": 2001,
        "era": "Millennium",
        "roles": {
            "Director": "Karan Johar",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Kajol",
            "Music Director": "Jatin-Lalit",
            "Writer": "Karan Johar",
        },
    },
    {
        "title": "Devdas",
        "year": 2002,
        "era": "Millennium",
        "roles": {
            "Director": "Sanjay Leela Bhansali",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Aishwarya Rai",
            "Music Director": "Ismail Darbar",
            "Writer": "Prakash Kapadia",
        },
    },
    {
        "title": "Company",
        "year": 2002,
        "era": "Millennium",
        "roles": {
            "Director": "Ram Gopal Varma",
            "Lead Male": "Ajay Devgn",
            "Lead Female": "Manisha Koirala",
            "Music Director": "Sandeep Chowta",
            "Writer": "Jaideep Sahni",
        },
    },
    {
        "title": "Kal Ho Naa Ho",
        "year": 2003,
        "era": "Millennium",
        "roles": {
            "Director": "Nikkhil Advani",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Preity Zinta",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Karan Johar",
        },
    },
    {
        "title": "Munna Bhai M.B.B.S.",
        "year": 2003,
        "era": "Millennium",
        "roles": {
            "Director": "Rajkumar Hirani",
            "Lead Male": "Sanjay Dutt",
            "Lead Female": "Gracy Singh",
            "Music Director": "Anu Malik",
            "Writer": "Rajkumar Hirani",
        },
    },
    {
        "title": "Swades",
        "year": 2004,
        "era": "Millennium",
        "roles": {
            "Director": "Ashutosh Gowariker",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Gayatri Joshi",
            "Music Director": "A. R. Rahman",
            "Writer": "M. G. Sathya",
        },
    },
    {
        "title": "Veer-Zaara",
        "year": 2004,
        "era": "Millennium",
        "roles": {
            "Director": "Yash Chopra",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Preity Zinta",
            "Music Director": "Madan Mohan",
            "Writer": "Aditya Chopra",
        },
    },
    {
        "title": "Black",
        "year": 2005,
        "era": "Millennium",
        "roles": {
            "Director": "Sanjay Leela Bhansali",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Rani Mukerji",
            "Music Director": "Monty Sharma",
            "Writer": "Sanjay Leela Bhansali",
        },
    },
    {
        "title": "Rang De Basanti",
        "year": 2006,
        "era": "Millennium",
        "roles": {
            "Director": "Rakeysh Omprakash Mehra",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Soha Ali Khan",
            "Music Director": "A. R. Rahman",
            "Writer": "Rensil D'Silva",
        },
    },
    {
        "title": "Lage Raho Munna Bhai",
        "year": 2006,
        "era": "Millennium",
        "roles": {
            "Director": "Rajkumar Hirani",
            "Lead Male": "Sanjay Dutt",
            "Lead Female": "Vidya Balan",
            "Music Director": "Shantanu Moitra",
            "Writer": "Rajkumar Hirani",
        },
    },
    {
        "title": "Taare Zameen Par",
        "year": 2007,
        "era": "Millennium",
        "roles": {
            "Director": "Aamir Khan",
            "Lead Male": "Darsheel Safary",
            "Lead Female": "Tisca Chopra",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Amole Gupte",
        },
    },
    {
        "title": "Jab We Met",
        "year": 2007,
        "era": "Millennium",
        "roles": {
            "Director": "Imtiaz Ali",
            "Lead Male": "Shahid Kapoor",
            "Lead Female": "Kareena Kapoor",
            "Music Director": "Pritam",
            "Writer": "Imtiaz Ali",
        },
    },
    {
        "title": "Ghajini",
        "year": 2008,
        "era": "Millennium",
        "roles": {
            "Director": "A. R. Murugadoss",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Asin",
            "Music Director": "A. R. Rahman",
            "Writer": "A. R. Murugadoss",
        },
    },
    {
        "title": "Rab Ne Bana Di Jodi",
        "year": 2008,
        "era": "Millennium",
        "roles": {
            "Director": "Aditya Chopra",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Anushka Sharma",
            "Music Director": "Salim-Sulaiman",
            "Writer": "Aditya Chopra",
        },
    },
    {
        "title": "3 Idiots",
        "year": 2009,
        "era": "Millennium",
        "roles": {
            "Director": "Rajkumar Hirani",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Kareena Kapoor",
            "Music Director": "Shantanu Moitra",
            "Writer": "Rajkumar Hirani",
        },
    },
    {
        "title": "Kaminey",
        "year": 2009,
        "era": "Millennium",
        "roles": {
            "Director": "Vishal Bhardwaj",
            "Lead Male": "Shahid Kapoor",
            "Lead Female": "Priyanka Chopra",
            "Music Director": "Vishal Bhardwaj",
            "Writer": "Vishal Bhardwaj",
        },
    },
    {
        "title": "Dabangg",
        "year": 2010,
        "era": "Modern",
        "roles": {
            "Director": "Abhinav Kashyap",
            "Lead Male": "Salman Khan",
            "Lead Female": "Sonakshi Sinha",
            "Music Director": "Sajid-Wajid",
            "Writer": "Dilip Shukla",
        },
    },
    {
        "title": "My Name Is Khan",
        "year": 2010,
        "era": "Modern",
        "roles": {
            "Director": "Karan Johar",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Kajol",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Shibani Bathija",
        },
    },
    {
        "title": "Zindagi Na Milegi Dobara",
        "year": 2011,
        "era": "Modern",
        "roles": {
            "Director": "Zoya Akhtar",
            "Lead Male": "Hrithik Roshan",
            "Lead Female": "Katrina Kaif",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Zoya Akhtar",
        },
    },
    {
        "title": "Kahaani",
        "year": 2012,
        "era": "Modern",
        "roles": {
            "Director": "Sujoy Ghosh",
            "Lead Male": "Parambrata Chattopadhyay",
            "Lead Female": "Vidya Balan",
            "Music Director": "Vishal-Shekhar",
            "Writer": "Sujoy Ghosh",
        },
    },
    {
        "title": "Barfi!",
        "year": 2012,
        "era": "Modern",
        "roles": {
            "Director": "Anurag Basu",
            "Lead Male": "Ranbir Kapoor",
            "Lead Female": "Priyanka Chopra",
            "Music Director": "Pritam",
            "Writer": "Anurag Basu",
        },
    },
    {
        "title": "Queen",
        "year": 2013,
        "era": "Modern",
        "roles": {
            "Director": "Vikas Bahl",
            "Lead Male": "Rajkummar Rao",
            "Lead Female": "Kangana Ranaut",
            "Music Director": "Amit Trivedi",
            "Writer": "Vikas Bahl",
        },
    },
    {
        "title": "Bhaag Milkha Bhaag",
        "year": 2013,
        "era": "Modern",
        "roles": {
            "Director": "Rakeysh Omprakash Mehra",
            "Lead Male": "Farhan Akhtar",
            "Lead Female": "Sonam Kapoor",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Prasoon Joshi",
        },
    },
    {
        "title": "PK",
        "year": 2014,
        "era": "Modern",
        "roles": {
            "Director": "Rajkumar Hirani",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Anushka Sharma",
            "Music Director": "Shantanu Moitra",
            "Writer": "Rajkumar Hirani",
        },
    },
    {
        "title": "Haider",
        "year": 2014,
        "era": "Modern",
        "roles": {
            "Director": "Vishal Bhardwaj",
            "Lead Male": "Shahid Kapoor",
            "Lead Female": "Shraddha Kapoor",
            "Music Director": "Vishal Bhardwaj",
            "Writer": "Vishal Bhardwaj",
        },
    },
    {
        "title": "Bajrangi Bhaijaan",
        "year": 2015,
        "era": "Modern",
        "roles": {
            "Director": "Kabir Khan",
            "Lead Male": "Salman Khan",
            "Lead Female": "Kareena Kapoor",
            "Music Director": "Pritam",
            "Writer": "K. V. Vijayendra Prasad",
        },
    },
    {
        "title": "Piku",
        "year": 2015,
        "era": "Modern",
        "roles": {
            "Director": "Shoojit Sircar",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Deepika Padukone",
            "Music Director": "Anupam Roy",
            "Writer": "Juhi Chaturvedi",
        },
    },
    {
        "title": "Dangal",
        "year": 2016,
        "era": "Modern",
        "roles": {
            "Director": "Nitesh Tiwari",
            "Lead Male": "Aamir Khan",
            "Lead Female": "Sakshi Tanwar",
            "Music Director": "Pritam",
            "Writer": "Nitesh Tiwari",
        },
    },
    {
        "title": "Pink",
        "year": 2016,
        "era": "Modern",
        "roles": {
            "Director": "Aniruddha Roy Chowdhury",
            "Lead Male": "Amitabh Bachchan",
            "Lead Female": "Taapsee Pannu",
            "Music Director": "Shantanu Moitra",
            "Writer": "Ritesh Shah",
        },
    },
    {
        "title": "Hindi Medium",
        "year": 2017,
        "era": "Modern",
        "roles": {
            "Director": "Saket Chaudhary",
            "Lead Male": "Irrfan Khan",
            "Lead Female": "Saba Qamar",
            "Music Director": "Sachin-Jigar",
            "Writer": "Zeenat Lakhani",
        },
    },
    {
        "title": "Andhadhun",
        "year": 2018,
        "era": "Modern",
        "roles": {
            "Director": "Sriram Raghavan",
            "Lead Male": "Ayushmann Khurrana",
            "Lead Female": "Radhika Apte",
            "Music Director": "Amit Trivedi",
            "Writer": "Sriram Raghavan",
        },
    },
    {
        "title": "Raazi",
        "year": 2018,
        "era": "Modern",
        "roles": {
            "Director": "Meghna Gulzar",
            "Lead Male": "Vicky Kaushal",
            "Lead Female": "Alia Bhatt",
            "Music Director": "Shankar-Ehsaan-Loy",
            "Writer": "Bhavani Iyer",
        },
    },
    {
        "title": "Gully Boy",
        "year": 2019,
        "era": "Modern",
        "roles": {
            "Director": "Zoya Akhtar",
            "Lead Male": "Ranveer Singh",
            "Lead Female": "Alia Bhatt",
            "Music Director": "Dub Sharma",
            "Writer": "Zoya Akhtar",
        },
    },
    {
        "title": "Article 15",
        "year": 2019,
        "era": "Modern",
        "roles": {
            "Director": "Anubhav Sinha",
            "Lead Male": "Ayushmann Khurrana",
            "Lead Female": "Isha Talwar",
            "Music Director": "Anurag Saikia",
            "Writer": "Gaurav Solanki",
        },
    },
    {
        "title": "Tanhaji",
        "year": 2020,
        "era": "Modern",
        "roles": {
            "Director": "Om Raut",
            "Lead Male": "Ajay Devgn",
            "Lead Female": "Kajol",
            "Music Director": "Ajay-Atul",
            "Writer": "Prakash Kapadia",
        },
    },
    {
        "title": "Thappad",
        "year": 2020,
        "era": "Modern",
        "roles": {
            "Director": "Anubhav Sinha",
            "Lead Male": "Pavail Gulati",
            "Lead Female": "Taapsee Pannu",
            "Music Director": "Anurag Saikia",
            "Writer": "Mrunmayee Lagoo",
        },
    },
    {
        "title": "Shershaah",
        "year": 2021,
        "era": "2021-2026",
        "roles": {
            "Director": "Vishnuvardhan",
            "Lead Male": "Sidharth Malhotra",
            "Lead Female": "Kiara Advani",
            "Music Director": "Tanishk Bagchi",
            "Writer": "Sandeep Shrivastava",
        },
    },
    {
        "title": "Sardar Udham",
        "year": 2021,
        "era": "2021-2026",
        "roles": {
            "Director": "Shoojit Sircar",
            "Lead Male": "Vicky Kaushal",
            "Lead Female": "Banita Sandhu",
            "Music Director": "Shantanu Moitra",
            "Writer": "Shubhendu Bhattacharya",
        },
    },
    {
        "title": "Sooryavanshi",
        "year": 2021,
        "era": "2021-2026",
        "roles": {
            "Director": "Rohit Shetty",
            "Lead Male": "Akshay Kumar",
            "Lead Female": "Katrina Kaif",
            "Music Director": "Tanishk Bagchi",
            "Writer": "Farhad Samji",
        },
    },
    {
        "title": "Gangubai Kathiawadi",
        "year": 2022,
        "era": "2021-2026",
        "roles": {
            "Director": "Sanjay Leela Bhansali",
            "Lead Male": "Shantanu Maheshwari",
            "Lead Female": "Alia Bhatt",
            "Music Director": "Sanjay Leela Bhansali",
            "Writer": "Utkarshini Vashishtha",
        },
    },
  
    },
    {
        "title": "Bhool Bhulaiyaa 2",
        "year": 2022,
        "era": "2021-2026",
        "roles": {
            "Director": "Anees Bazmee",
            "Lead Male": "Kartik Aaryan",
            "Lead Female": "Kiara Advani",
            "Music Director": "Pritam",
            "Writer": "Aakash Kaushik",
        },
    },
    {
        "title": "RRR",
        "year": 2022,
        "era": "2021-2026",
        "roles": {
            "Director": "S. S. Rajamouli",
            "Lead Male": "Ram Charan",
            "Lead Female": "Alia Bhatt",
            "Music Director": "M. M. Keeravani",
            "Writer": "K. V. Vijayendra Prasad",
        },
    },
    {
        "title": "Drishyam 2",
        "year": 2022,
        "era": "2021-2026",
        "roles": {
            "Director": "Abhishek Pathak",
            "Lead Male": "Ajay Devgn",
            "Lead Female": "Shriya Saran",
            "Music Director": "Devi Sri Prasad",
            "Writer": "Aamil Keeyan Khan",
        },
    },
    {
        "title": "Brahmastra Part One: Shiva",
        "year": 2022,
        "era": "2021-2026",
        "roles": {
            "Director": "Ayan Mukerji",
            "Lead Male": "Ranbir Kapoor",
            "Lead Female": "Alia Bhatt",
            "Music Director": "Pritam",
            "Writer": "Ayan Mukerji",
        },
    },
    {
        "title": "Pathaan",
        "year": 2023,
        "era": "2021-2026",
        "roles": {
            "Director": "Siddharth Anand",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Deepika Padukone",
            "Music Director": "Vishal-Shekhar",
            "Writer": "Shridhar Raghavan",
        },
    },
    {
        "title": "Jawan",
        "year": 2023,
        "era": "2021-2026",
        "roles": {
            "Director": "Atlee",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Nayanthara",
            "Music Director": "Anirudh Ravichander",
            "Writer": "Atlee",
        },
    },
    {
        "title": "12th Fail",
        "year": 2023,
        "era": "2021-2026",
        "roles": {
            "Director": "Vidhu Vinod Chopra",
            "Lead Male": "Vikrant Massey",
            "Lead Female": "Medha Shankr",
            "Music Director": "Shantanu Moitra",
            "Writer": "Vidhu Vinod Chopra",
        },
    },
    {
        "title": "Animal",
        "year": 2023,
        "era": "2021-2026",
        "roles": {
            "Director": "Sandeep Reddy Vanga",
            "Lead Male": "Ranbir Kapoor",
            "Lead Female": "Rashmika Mandanna",
            "Music Director": "Harshavardhan Rameshwar",
            "Writer": "Sandeep Reddy Vanga",
        },
    },
    {
        "title": "Dunki",
        "year": 2023,
        "era": "2021-2026",
        "roles": {
            "Director": "Rajkumar Hirani",
            "Lead Male": "Shah Rukh Khan",
            "Lead Female": "Taapsee Pannu",
            "Music Director": "Pritam",
            "Writer": "Abhijat Joshi",
        },
    },
    {
        "title": "Fighter",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Siddharth Anand",
            "Lead Male": "Hrithik Roshan",
            "Lead Female": "Deepika Padukone",
            "Music Director": "Vishal-Shekhar",
            "Writer": "Ramon Chibb",
        },
    },
    {
        "title": "Munjya",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Aditya Sarpotdar",
            "Lead Male": "Abhay Verma",
            "Lead Female": "Sharvari",
            "Music Director": "Sachin-Jigar",
            "Writer": "Niren Bhatt",
        },
    },
    {
        "title": "Stree 2",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Amar Kaushik",
            "Lead Male": "Rajkummar Rao",
            "Lead Female": "Shraddha Kapoor",
            "Music Director": "Sachin-Jigar",
            "Writer": "Niren Bhatt",
        },
    },
    {
        "title": "Kalki 2898 AD",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Nag Ashwin",
            "Lead Male": "Prabhas",
            "Lead Female": "Deepika Padukone",
            "Music Director": "Santhosh Narayanan",
            "Writer": "Nag Ashwin",
        },
    },
    {
        "title": "Pushpa 2: The Rule",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Sukumar",
            "Lead Male": "Allu Arjun",
            "Lead Female": "Rashmika Mandanna",
            "Music Director": "Devi Sri Prasad",
            "Writer": "Sukumar",
        },
    },
    {
        "title": "Singham Again",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Rohit Shetty",
            "Lead Male": "Ajay Devgn",
            "Lead Female": "Kareena Kapoor",
            "Music Director": "Ravi Basrur",
            "Writer": "Kshitij Patwardhan",
        },
    },
    {
        "title": "Laapataa Ladies",
        "year": 2024,
        "era": "2021-2026",
        "roles": {
            "Director": "Kiran Rao",
            "Lead Male": "Sparsh Shrivastava",
            "Lead Female": "Nitanshi Goel",
            "Music Director": "Ram Sampath",
            "Writer": "Sneha Desai",
        },
    },
]
